version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - "> 4.8"
  - dependency-name: phpunit/phpunit
    versions:
    - "< 7, >= 6.a"
  - dependency-name: slim/slim
    versions:
    - ">= 4.a, < 5"
